### ISSUE TITLE
non-stopping change detection

### ISSUE THREAD

**Issue by HymanZHAN** [edbzn/rx-angular-todo-mvc#2]
Hi,

I just pulled your repo to play around, but I noticed some performance issue. Change detection keeps running all the time, even when I am doing nothing.

![image](https://user-images.githubusercontent.com/26806995/192125373-a8896ab4-9711-4f58-8033-7fe7ddec1c7e.png)
 
This is the Angular Dev Tool profile:

[NgDevTools-Profile-20220925T101449.zip](https://github.com/edbzn/rx-angular-todo-mvc/files/9639879/NgDevTools-Profile-20220925T101449.zip)

**Comment by edbzn** [comment]
Hi @HymanZHAN, nice catch! it seems I introduced a bug in the `TodoComponent`, just fixed it.
