### ISSUE TITLE
Using combineLastest to build vm it's a good practice?

### ISSUE THREAD

**Issue by wizardnet972** [edbzn/rx-angular-todo-mvc#3]
I'm wondering if it's okay to use `combineLastest` to build a `vm`?

Because every time `vm$` observable is changing the [inner DOM ](https://github.com/edbzn/rx-angular-todo-mvc/blob/main/projects/todo-mvc/src/app/todo-list.component.ts#L27) is rebuilt.
 
Am I wrong? 

```
<ng-container *rxLet="todoService.vm$ as vm">
... 
</ng-container>
```

**Comment by edbzn** [comment]
@wizardnet972 Hey sorry I haven't seen this issue until now, you are right `combineLatest` is not optimized, we plan to introduce a new operator for building the vm https://github.com/rx-angular/rx-angular/pull/1192.
